name: "Update Akshare"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: bash packages/python/akshare/update.sh
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'chore(akshare): update akshare'
